identifier: config.config.Config
trainer:
    identifier: config.config.TrainerConfig
    name: ngp
    eval_interval: 5
    use_checkpoint: latest
    workspace: workspace/hotspot_lambda_warm
    use_tensorboardX: true
    max_keep_ckpt: 2
    local_rank: 0
    world_size: 1
    ema_decay: 0.95
    boundary_loss_weight: 1000
    eikonal_loss_weight: 0.1
    sign_loss_weight: 0
    heat_loss_weight: 5
    h: 0.0001
    heat_loss_lambda: 5
    resolution: 512
data:
    identifier: config.config.DataConfig
    dataset_path: data/armadillo.obj
    train_size: 100
    valid_size: 1
    num_samples: 131072
optimizer:
    identifier: config.config.OptimizerConfig
    type: Adam
    lr: 0.001
    weight_decay: 1e-06
    betas:
        - 0.9
        - 0.99
    eps: 1e-15
scheduler:
    identifier: config.config.SchedulerConfig
    type: StepLR
    step_size: 10
    gamma: 0.1
seed: 0
test: false
epochs: 25
